# Generated by Django 4.2.2 on 2023-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_post',
            name='comment',
        ),
        migrations.AlterField(
            model_name='board_comment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='board_post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
