# Generated by Django 4.2.1 on 2023-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_board_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_post',
            name='category',
            field=models.CharField(choices=[('1', '질문'), ('2', '소통'), ('3', '정보'), ('4', '일상')], default='1', max_length=1, verbose_name='카테고리'),
        ),
    ]
