# Generated by Django 4.2.1 on 2023-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="이름"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                ("nickname", models.CharField(max_length=100, verbose_name="닉네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "phone",
                    models.CharField(default="", max_length=20, verbose_name="전화번호"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
