# Generated by Django 4.2.1 on 2023-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="token",
            field=models.TextField(null=True, verbose_name="토큰"),
        ),
    ]
