# Generated by Django 4.2.1 on 2023-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_member_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="token",
            field=models.TextField(default="", verbose_name="토큰"),
        ),
    ]
