# Generated by Django 4.2.1 on 2023-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_member_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(default="", max_length=100, verbose_name="주소"),
        ),
        migrations.AddField(
            model_name="member",
            name="age",
            field=models.IntegerField(default=0, verbose_name="나이"),
        ),
        migrations.AddField(
            model_name="member",
            name="review_star",
            field=models.IntegerField(default=0, verbose_name="최근받은점수"),
        ),
    ]
