# Generated by Django 4.2.2 on 2023-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, verbose_name='실명')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member_sns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
