# Generated by Django 4.2.2 on 2023-07-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='petsitters_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('1', '일반'), ('2', '프리미엄')], default='1', max_length=1, verbose_name='시터등급')),
                ('image', models.ImageField(blank=True, null=True, upload_to='petsitters/images/', verbose_name='이미지')),
                ('during', models.DateField(null=True, verbose_name='임보기간')),
                ('pay', models.IntegerField(default=0, verbose_name='페이')),
                ('address', models.CharField(default='', max_length=100, verbose_name='주소')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='petsitters_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, verbose_name='내용')),
                ('likes', models.ManyToManyField(to='customers.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsitters.petsitters_post')),
            ],
        ),
    ]
