# Generated by Django 4.2.2 on 2023-07-05 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='petsitters_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='작성자')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.CharField(max_length=200, verbose_name='임보기간')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='petsitters_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, verbose_name='내용')),
                ('likes', models.ManyToManyField(to='customers.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsitters.petsitters_post')),
            ],
        ),
    ]
