# Generated by Django 4.2.2 on 2023-07-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitters_post',
            name='comment',
            field=models.TextField(null=True, verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='petsitters_post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petsitters_post',
            name='content',
            field=models.CharField(max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='petsitters_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petsitters_post',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
