# Generated by Django 4.2.2 on 2023-07-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0002_petsitters_post_comment_petsitters_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitters_post',
            old_name='member_id',
            new_name='member',
        ),
    ]
