# Generated by Django 4.2.1 on 2023-07-06 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petsitters', '0002_remove_petsitters_post_during_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitters_comment',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
