# Generated by Django 4.2.1 on 2023-07-07 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petsitters', '0003_alter_petsitters_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitters_comment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='petsitters_post',
            name='category',
            field=models.CharField(choices=[('1', '시터신청'), ('2', '시터찾기')], default='1', max_length=1, verbose_name='구분'),
        ),
        migrations.CreateModel(
            name='petsitters_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='petsitters/images/', verbose_name='본인사진')),
                ('rnn', models.CharField(max_length=14, null=True, verbose_name='주민번호')),
                ('address', models.CharField(default='', max_length=200, verbose_name='주소')),
                ('lisence_hold', models.CharField(max_length=3, verbose_name='자격증 보유여부')),
                ('pet_experience', models.CharField(max_length=3, verbose_name='반려동물 경험')),
                ('pet_species', models.CharField(max_length=50, verbose_name='동물 종류')),
                ('exprience_essay', models.TextField(verbose_name='임보 경험')),
                ('allergy_essay', models.TextField(verbose_name='알레르기 경험')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
        ),
    ]
