# Generated by Django 4.2.2 on 2023-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0004_petsitters_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitters_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petsitters/images/', verbose_name='이미지'),
        ),
    ]
