# Generated by Django 4.2.1 on 2023-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0004_remove_petsitters_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitters_apply',
            name='lisence_hold',
            field=models.CharField(choices=[('1', '네'), ('2', '아니요')], max_length=100, verbose_name='자격증 보유여부'),
        ),
        migrations.AlterField(
            model_name='petsitters_apply',
            name='pet_experience',
            field=models.CharField(choices=[('1', '네'), ('2', '아니요')], max_length=100, verbose_name='반려동물 경험'),
        ),
        migrations.AlterField(
            model_name='petsitters_apply',
            name='pet_species',
            field=models.CharField(choices=[('1', '고양이'), ('2', '개'), ('3', '조류'), ('4', '기타')], max_length=50, verbose_name='동물 종류'),
        ),
    ]
