# Generated by Django 4.2.1 on 2023-07-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0005_alter_petsitters_apply_lisence_hold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitters_post',
            old_name='data_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='petsitters_post',
            old_name='data_start',
            new_name='date_start',
        ),
    ]
