# Generated by Django 4.2.1 on 2023-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0006_rename_data_end_petsitters_post_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitters_post',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='구분'),
        ),
    ]
