# Generated by Django 4.2.1 on 2023-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0008_alter_petsitters_apply_lisence_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitters_apply',
            name='family',
            field=models.CharField(default='', max_length=20, verbose_name='가구원'),
        ),
        migrations.AddField(
            model_name='petsitters_apply',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='petsitters_apply',
            name='rnn',
            field=models.CharField(default='', max_length=20, verbose_name='주민번호'),
        ),
    ]
